# Generated by Django 3.2.14 on 2022-07-21 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='inquiry',
            new_name='subject',
        ),
    ]
