# Generated by Django 3.2.14 on 2022-07-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_rename_inquiry_contactmodel_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('title', models.CharField(default='', max_length=120)),
                ('about', models.CharField(default='', max_length=220)),
            ],
        ),
    ]
